name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  REACT_APP_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.REACT_APP_CONTENTFUL_ACCESS_TOKEN }}
  REACT_APP_CONTENFUL_SPACE_ID: ${{ secrets.REACT_APP_CONTENFUL_SPACE_ID }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-node@v6
      with:
        # Version Spec of the version to use in SemVer notation.
        # It also admits such aliases as lts/*, latest, nightly and canary builds
        # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
      node-version: '16'

    - uses: actions/checkout@v1
      with:
       persist-credentials: false
    - run: git config --global user.email ${{ secrets.USER_EMAIL }}
    - run: git config --global user.name ${{ secrets.USER_NAME }}

    - name: Build
      run: |
        npm install
        npm run build
  
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
